ARG TAP_BASE_IMAGE
FROM ${TAP_BASE_IMAGE}

USER root
COPY tap-entrypoint.sh /usr/local/bin/skypulse-tap-entrypoint
RUN chmod 0555 /usr/local/bin/skypulse-tap-entrypoint
USER 65534:65534

ENTRYPOINT ["/usr/local/bin/skypulse-tap-entrypoint"]
CMD ["run"]
