<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" />
    <PackageReference Include="Microsoft.Orleans.Persistence.Memory" />
    <PackageReference Include="Microsoft.Orleans.Persistence.Redis" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Infrastructure/PostgreSql/*.sql" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../eng/compatibility-manifest.json"
          Link="compatibility-manifest.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../eng/public-api.txt"
          Link="public-api.txt"
          CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../../eng/public-api/PublicApiManifest.cs"
             Link="Infrastructure/PublicApiManifest.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Orleans.SearchableStorage/Orleans.SearchableStorage.csproj" />
  </ItemGroup>
</Project>
