using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Orleans.SearchableStorage.ApiContract;

internal static class PublicApiManifest
{
    private static readonly NullabilityInfoContext Nullability = new();
    private static readonly Regex ArityPattern = new(
        "`[0-9]+",
        RegexOptions.CultureInvariant);
    private static readonly HashSet<string> ContractAttributeNames = new(StringComparer.Ordinal)
    {
        "System.Diagnostics.CodeAnalysis.AllowNullAttribute",
        "System.Diagnostics.CodeAnalysis.DisallowNullAttribute",
        "System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute",
        "System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute",
        "System.Diagnostics.CodeAnalysis.ExperimentalAttribute",
        "System.Diagnostics.CodeAnalysis.MaybeNullAttribute",
        "System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute",
        "System.Diagnostics.CodeAnalysis.MemberNotNullAttribute",
        "System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute",
        "System.Diagnostics.CodeAnalysis.NotNullAttribute",
        "System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute",
        "System.Diagnostics.CodeAnalysis.NotNullWhenAttribute",
        "System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute",
        "System.Diagnostics.CodeAnalysis.RequiresUnreferencedCodeAttribute",
        "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute",
        "System.Diagnostics.CodeAnalysis.StringSyntaxAttribute",
        "System.Diagnostics.CodeAnalysis.UnscopedRefAttribute",
        "System.Runtime.CompilerServices.CallerArgumentExpressionAttribute",
        "System.Runtime.CompilerServices.CallerFilePathAttribute",
        "System.Runtime.CompilerServices.CallerLineNumberAttribute",
        "System.Runtime.CompilerServices.CallerMemberNameAttribute",
        "System.Runtime.CompilerServices.CollectionBuilderAttribute",
        "System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute",
        "System.Runtime.CompilerServices.DynamicAttribute",
        "System.Runtime.CompilerServices.EnumeratorCancellationAttribute",
        "System.Runtime.CompilerServices.InterpolatedStringHandlerArgumentAttribute",
        "System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute",
        "System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute",
        "System.Runtime.CompilerServices.ScopedRefAttribute",
        "System.Runtime.CompilerServices.TupleElementNamesAttribute",
    };

    public static string Generate(Assembly assembly)
    {
        ArgumentNullException.ThrowIfNull(assembly);
        var builder = new StringBuilder();
        builder.AppendLine("# Orleans.SearchableStorage public API manifest v1");
        builder.AppendLine("# Generated by eng/public-api-generator; review every diff.");

        var types = assembly.GetTypes()
            .Where(IsShippingType)
            .OrderBy(FormatType, StringComparer.Ordinal);
        foreach (var type in types)
        {
            AppendType(builder, type);
        }

        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    internal static string GenerateType(Type type)
    {
        ArgumentNullException.ThrowIfNull(type);
        var builder = new StringBuilder();
        AppendType(builder, type);
        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void AppendType(StringBuilder builder, Type type)
    {
        builder.Append("type ").Append(FormatTypeDeclaration(type)).AppendLine();
        if (type.BaseType is not null)
        {
            builder.Append("  base ").Append(FormatType(type.BaseType)).AppendLine();
        }
        if (type.IsEnum)
        {
            builder.Append("  underlying ")
                .Append(FormatType(Enum.GetUnderlyingType(type)))
                .AppendLine();
        }

        foreach (var implemented in type.GetInterfaces().OrderBy(FormatType, StringComparer.Ordinal))
        {
            builder.Append("  interface ").Append(FormatType(implemented)).AppendLine();
        }

        foreach (var constraint in FormatGenericConstraints(type.GetGenericArguments()))
        {
            builder.Append("  generic ").Append(constraint).AppendLine();
        }

        foreach (var member in FormatDeclaredMembers(type).Order(StringComparer.Ordinal))
        {
            builder.Append("  ").Append(member).AppendLine();
        }
    }

    private static bool IsShippingType(Type type)
    {
        // Orleans emits public serializer implementation types into its reserved OrleansCodeGen
        // namespace. They are not callable package surface and change with the generator. All other
        // effectively public/protected types are intentional API, including future namespaces.
        if (type.Namespace?.StartsWith("OrleansCodeGen.", StringComparison.Ordinal) == true)
        {
            return false;
        }

        var visible = type.IsPublic
            || type.IsNestedPublic
            || type.IsNestedFamily
            || type.IsNestedFamORAssem;
        return visible && (type.DeclaringType is null || IsShippingType(type.DeclaringType));
    }

    private static IEnumerable<string> FormatDeclaredMembers(Type type)
    {
        const BindingFlags declared = BindingFlags.Public
            | BindingFlags.NonPublic
            | BindingFlags.Instance
            | BindingFlags.Static
            | BindingFlags.DeclaredOnly;

        var properties = type.GetProperties(declared);
        var events = type.GetEvents(declared);
        var accessors = properties
            .SelectMany(static property => property.GetAccessors(nonPublic: true))
            .Concat(events.SelectMany(static @event =>
            {
                var methods = new List<MethodInfo>();
                if (@event.AddMethod is not null)
                {
                    methods.Add(@event.AddMethod);
                }
                if (@event.RemoveMethod is not null)
                {
                    methods.Add(@event.RemoveMethod);
                }
                if (@event.RaiseMethod is not null)
                {
                    methods.Add(@event.RaiseMethod);
                }
                return methods;
            }))
            .ToHashSet();

        foreach (var constructor in type.GetConstructors(declared).Where(IsShippingMethod))
        {
            yield return FormatConstructor(constructor);
        }

        foreach (var field in type.GetFields(declared).Where(IsShippingField))
        {
            yield return FormatField(field);
        }

        foreach (var property in properties.Where(IsShippingProperty))
        {
            yield return FormatProperty(property);
        }

        foreach (var @event in events.Where(IsShippingEvent))
        {
            yield return FormatEvent(@event);
        }

        foreach (var method in type.GetMethods(declared)
                     .Where(method => IsShippingMethod(method) && !accessors.Contains(method)))
        {
            yield return FormatMethod(method);
        }
    }

    private static string FormatTypeDeclaration(Type type)
    {
        var modifiers = new List<string> { TypeAccessibility(type) };
        if (type.IsClass && type.IsAbstract && type.IsSealed)
        {
            modifiers.Add("static");
        }
        else
        {
            if (type.IsAbstract && !type.IsInterface)
            {
                modifiers.Add("abstract");
            }
            if (type.IsSealed && !type.IsValueType && !IsDelegate(type))
            {
                modifiers.Add("sealed");
            }
        }
        if (type.IsValueType && type.IsDefined(typeof(IsReadOnlyAttribute), inherit: false))
        {
            modifiers.Add("readonly");
        }
        if (type.IsByRefLike)
        {
            modifiers.Add("ref");
        }

        modifiers.Add(TypeKind(type));
        modifiers.Add(FormatType(type));
        return FormatSignificantAttributes(type) + string.Join(' ', modifiers);
    }

    private static string TypeAccessibility(Type type)
    {
        if (type.IsPublic || type.IsNestedPublic)
        {
            return "public";
        }
        if (type.IsNestedFamORAssem)
        {
            return "protected internal";
        }
        if (type.IsNestedFamily)
        {
            return "protected";
        }
        throw new InvalidOperationException($"Type {type} is not shipping API.");
    }

    private static string TypeKind(Type type)
    {
        if (type.IsInterface)
        {
            return "interface";
        }
        if (type.IsEnum)
        {
            return "enum";
        }
        if (IsDelegate(type))
        {
            return "delegate";
        }
        return type.IsValueType ? "struct" : "class";
    }

    private static bool IsDelegate(Type type) =>
        type.BaseType is not null && typeof(MulticastDelegate).IsAssignableFrom(type.BaseType);

    private static bool IsShippingMethod(MethodBase method) =>
        method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly;

    private static bool IsShippingField(FieldInfo field) =>
        !field.IsSpecialName && (field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly);

    private static bool IsShippingProperty(PropertyInfo property) =>
        property.GetAccessors(nonPublic: true).Any(IsShippingMethod);

    private static bool IsShippingEvent(EventInfo @event) =>
        new[] { @event.AddMethod, @event.RemoveMethod, @event.RaiseMethod }
            .OfType<MethodInfo>()
            .Any(IsShippingMethod);

    private static string FormatConstructor(ConstructorInfo constructor)
    {
        return string.Concat(
            "ctor ",
            FormatSignificantAttributes(constructor),
            MethodAccessibility(constructor),
            constructor.IsStatic ? " static" : string.Empty,
            " ",
            FormatType(constructor.DeclaringType!),
            "(",
            FormatParameters(constructor, constructor.GetParameters()),
            ")");
    }

    private static string FormatMethod(MethodInfo method)
    {
        var modifiers = new List<string> { "method", MethodAccessibility(method) };
        if (method.IsStatic)
        {
            modifiers.Add("static");
        }
        if (method.IsAbstract)
        {
            modifiers.Add("abstract");
        }
        else if (method.IsVirtual)
        {
            var isOverride = method.GetBaseDefinition() != method;
            if (isOverride && method.IsFinal)
            {
                modifiers.Add("sealed");
            }
            modifiers.Add(isOverride ? "override" : "virtual");
        }

        var returnType = FormatParameterType(method.ReturnParameter, isReturn: true);
        var genericArguments = method.IsGenericMethodDefinition ? method.GetGenericArguments() : [];
        var genericNames = genericArguments.Length == 0
            ? string.Empty
            : $"<{string.Join(',', genericArguments.Select(static argument => argument.Name))}>";
        var constraints = FormatGenericConstraints(genericArguments).ToArray();
        var constraintText = constraints.Length == 0
            ? string.Empty
            : " where " + string.Join("; ", constraints);
        return string.Concat(
            string.Join(' ', modifiers),
            " ",
            FormatSignificantAttributes(method),
            returnType,
            " ",
            method.Name,
            genericNames,
            "(",
            FormatParameters(method, method.GetParameters()),
            ")",
            constraintText);
    }

    private static string FormatField(FieldInfo field)
    {
        var modifiers = new List<string> { "field", FieldAccessibility(field) };
        if (field.IsLiteral)
        {
            modifiers.Add("const");
        }
        else
        {
            if (field.IsStatic)
            {
                modifiers.Add("static");
            }
            if (field.IsInitOnly)
            {
                modifiers.Add("readonly");
            }
        }
        if (field.IsRequired())
        {
            modifiers.Add("required");
        }

        var value = field.IsLiteral
            ? " = " + FormatDefault(field.GetRawConstantValue(), field.FieldType)
            : string.Empty;
        return string.Concat(
            string.Join(' ', modifiers),
            " ",
            FormatSignificantAttributes(field),
            FormatType(field.FieldType, Nullability.Create(field)),
            " ",
            field.Name,
            value);
    }

    private static string FormatProperty(PropertyInfo property)
    {
        var accessors = property.GetAccessors(nonPublic: true).Where(IsShippingMethod).ToArray();
        var modifiers = new List<string>
        {
            "property",
            MostVisibleAccessibility(accessors),
        };
        if (accessors.Any(static accessor => accessor.IsStatic))
        {
            modifiers.Add("static");
        }
        AddVirtualModifiers(modifiers, accessors);
        if (property.IsRequired())
        {
            modifiers.Add("required");
        }

        var nullability = Nullability.Create(property);
        var indexParameters = property.GetIndexParameters();
        var name = indexParameters.Length == 0
            ? property.Name
            : $"this[{FormatParameters(null, indexParameters)}]";
        var accessorText = new List<string>();
        if (property.GetMethod is not null && IsShippingMethod(property.GetMethod))
        {
            accessorText.Add(AccessorPrefix(property.GetMethod, accessors) + "get;");
        }
        if (property.SetMethod is not null && IsShippingMethod(property.SetMethod))
        {
            var initOnly = property.SetMethod.ReturnParameter
                .GetRequiredCustomModifiers()
                .Contains(typeof(IsExternalInit));
            var writeContract = FormatPropertyWriteContract(property, nullability);
            accessorText.Add(
                AccessorPrefix(property.SetMethod, accessors)
                + writeContract
                + (initOnly ? "init;" : "set;"));
        }

        return string.Concat(
            string.Join(' ', modifiers),
            " ",
            FormatSignificantAttributes(property),
            FormatType(property.PropertyType, nullability),
            " ",
            name,
            " { ",
            string.Join(' ', accessorText),
            " }");
    }

    private static string FormatPropertyWriteContract(PropertyInfo property, NullabilityInfo nullability)
    {
        var values = new List<string>();
        if (nullability.WriteState != nullability.ReadState)
        {
            values.Add("write-nullability=" + nullability.WriteState.ToString().ToLowerInvariant());
        }

        var valueParameter = property.SetMethod?.GetParameters().LastOrDefault();
        if (valueParameter is not null)
        {
            var attributes = FormatContractAttributePrefix(valueParameter.GetCustomAttributesData()).TrimEnd();
            if (attributes.Length > 0)
            {
                values.Add("value-attributes=" + attributes);
            }
        }

        return values.Count == 0 ? string.Empty : "[" + string.Join(';', values) + "] ";
    }

    private static string FormatEvent(EventInfo @event)
    {
        var accessors = new[] { @event.AddMethod, @event.RemoveMethod, @event.RaiseMethod }
            .OfType<MethodInfo>()
            .Where(IsShippingMethod)
            .ToArray();
        var modifiers = new List<string> { "event", MostVisibleAccessibility(accessors) };
        if (accessors.Any(static accessor => accessor.IsStatic))
        {
            modifiers.Add("static");
        }
        AddVirtualModifiers(modifiers, accessors);
        var nullability = Nullability.Create(@event);
        return string.Concat(
            string.Join(' ', modifiers),
            " ",
            FormatSignificantAttributes(@event),
            FormatType(@event.EventHandlerType!, nullability),
            " ",
            @event.Name);
    }

    private static string FormatParameters(MethodBase? method, IReadOnlyList<ParameterInfo> parameters)
    {
        return string.Join(
            ", ",
            parameters.Select((parameter, index) => FormatParameter(method, parameter, index)));
    }

    private static string FormatParameter(MethodBase? method, ParameterInfo parameter, int index)
    {
        var modifiers = new List<string>();
        if (method is not null
            && index == 0
            && method.IsDefined(typeof(ExtensionAttribute), inherit: false))
        {
            modifiers.Add("this");
        }
        if (parameter.IsDefined(typeof(ParamArrayAttribute), inherit: false))
        {
            modifiers.Add("params");
        }
        if (parameter.ParameterType.IsByRef)
        {
            modifiers.Add(parameter.IsOut ? "out" : parameter.IsIn ? "in" : "ref");
        }

        var prefix = modifiers.Count == 0 ? string.Empty : string.Join(' ', modifiers) + " ";
        var defaultValue = parameter.HasDefaultValue
            ? " = " + FormatDefault(parameter.DefaultValue, parameter.ParameterType)
            : parameter.IsOptional ? " = <missing>" : string.Empty;
        return string.Concat(prefix, FormatParameterType(parameter), " ", parameter.Name, defaultValue);
    }

    private static string FormatParameterType(ParameterInfo parameter, bool isReturn = false)
    {
        var type = parameter.ParameterType;
        var prefix = string.Empty;
        if (type.IsByRef)
        {
            type = type.GetElementType()!;
            if (isReturn)
            {
                var readOnly = parameter.GetRequiredCustomModifiers().Contains(typeof(IsReadOnlyAttribute));
                prefix = readOnly ? "ref readonly " : "ref ";
            }
        }
        return FormatContractAttributePrefix(parameter.GetCustomAttributesData())
            + prefix
            + FormatType(type, Nullability.Create(parameter));
    }

    private static string MethodAccessibility(MethodBase method)
    {
        if (method.IsPublic)
        {
            return "public";
        }
        if (method.IsFamilyOrAssembly)
        {
            return "protected internal";
        }
        if (method.IsFamily)
        {
            return "protected";
        }
        throw new InvalidOperationException($"Method {method} is not shipping API.");
    }

    private static string FieldAccessibility(FieldInfo field)
    {
        if (field.IsPublic)
        {
            return "public";
        }
        if (field.IsFamilyOrAssembly)
        {
            return "protected internal";
        }
        if (field.IsFamily)
        {
            return "protected";
        }
        throw new InvalidOperationException($"Field {field} is not shipping API.");
    }

    private static string MostVisibleAccessibility(IEnumerable<MethodInfo> methods)
    {
        var accessibilities = methods.Select(MethodAccessibility).ToHashSet(StringComparer.Ordinal);
        if (accessibilities.Contains("public"))
        {
            return "public";
        }
        return accessibilities.Contains("protected internal") ? "protected internal" : "protected";
    }

    private static string AccessorPrefix(MethodInfo accessor, IReadOnlyCollection<MethodInfo> siblings)
    {
        var propertyAccessibility = MostVisibleAccessibility(siblings);
        var accessorAccessibility = MethodAccessibility(accessor);
        return accessorAccessibility == propertyAccessibility ? string.Empty : accessorAccessibility + " ";
    }

    private static void AddVirtualModifiers(List<string> modifiers, IReadOnlyCollection<MethodInfo> accessors)
    {
        var representative = accessors
            .OrderBy(static accessor => accessor.Name, StringComparer.Ordinal)
            .FirstOrDefault(static accessor => accessor.IsAbstract || accessor.IsVirtual);
        if (representative is null)
        {
            return;
        }
        if (representative.IsAbstract)
        {
            modifiers.Add("abstract");
            return;
        }

        var isOverride = representative.GetBaseDefinition() != representative;
        if (isOverride && representative.IsFinal)
        {
            modifiers.Add("sealed");
        }
        modifiers.Add(isOverride ? "override" : "virtual");
    }

    private static IEnumerable<string> FormatGenericConstraints(IEnumerable<Type> parameters)
    {
        foreach (var parameter in parameters.Where(static parameter => parameter.IsGenericParameter))
        {
            var values = new List<string>();
            var attributes = parameter.GenericParameterAttributes;
            var variance = attributes & GenericParameterAttributes.VarianceMask;
            if (variance == GenericParameterAttributes.Covariant)
            {
                values.Add("out");
            }
            else if (variance == GenericParameterAttributes.Contravariant)
            {
                values.Add("in");
            }

            var special = attributes & GenericParameterAttributes.SpecialConstraintMask;
            var nullableConstraint = GetNullableConstraint(parameter);
            if (special.HasFlag(GenericParameterAttributes.ReferenceTypeConstraint))
            {
                values.Add(nullableConstraint == 2 ? "class?" : "class");
            }
            if (special.HasFlag(GenericParameterAttributes.NotNullableValueTypeConstraint))
            {
                values.Add(HasAttribute(parameter, "System.Runtime.CompilerServices.IsUnmanagedAttribute")
                    ? "unmanaged"
                    : "struct");
            }
            else if (!special.HasFlag(GenericParameterAttributes.ReferenceTypeConstraint)
                     && HasAttribute(parameter, "System.Runtime.CompilerServices.DefaultConstraintAttribute"))
            {
                values.Add("default");
            }
            else if (!special.HasFlag(GenericParameterAttributes.ReferenceTypeConstraint)
                     && nullableConstraint == 1)
            {
                values.Add("notnull");
            }
            values.AddRange(parameter.GetGenericParameterConstraints()
                .Where(static constraint => constraint != typeof(ValueType))
                .Select(FormatType)
                .Order(StringComparer.Ordinal));
            if (special.HasFlag(GenericParameterAttributes.DefaultConstructorConstraint)
                && !special.HasFlag(GenericParameterAttributes.NotNullableValueTypeConstraint))
            {
                values.Add("new()");
            }
            if (attributes.HasFlag(GenericParameterAttributes.AllowByRefLike))
            {
                values.Add("allows ref struct");
            }

            if (values.Count > 0)
            {
                yield return $"{parameter.Name} : {string.Join(", ", values)}";
            }
        }
    }

    private static string FormatType(Type type) => FormatType(type, null);

    private static string FormatType(Type type, NullabilityInfo? nullability)
    {
        if (type.IsByRef)
        {
            return FormatType(type.GetElementType()!, nullability?.ElementType);
        }
        if (type.IsPointer)
        {
            return FormatType(type.GetElementType()!, nullability?.ElementType) + "*";
        }
        if (type.IsArray)
        {
            var commas = new string(',', type.GetArrayRank() - 1);
            var array = FormatType(type.GetElementType()!, nullability?.ElementType) + $"[{commas}]";
            return AppendNullable(array, type, nullability);
        }
        if (type.IsGenericParameter)
        {
            return AppendNullable(type.Name, type, nullability);
        }
        if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
        {
            var argumentNullability = nullability?.GenericTypeArguments.FirstOrDefault();
            return FormatType(type.GetGenericArguments()[0], argumentNullability) + "?";
        }

        var definition = type.IsGenericType ? type.GetGenericTypeDefinition() : type;
        var name = ArityPattern.Replace(
            (definition.FullName ?? definition.Name).Replace('+', '.'),
            string.Empty);
        if (type.IsGenericType)
        {
            var arguments = type.GetGenericArguments();
            var nullabilityArguments = nullability?.GenericTypeArguments ?? [];
            name += "<" + string.Join(
                ",",
                arguments.Select((argument, index) => FormatType(
                    argument,
                    index < nullabilityArguments.Length ? nullabilityArguments[index] : null))) + ">";
        }
        return AppendNullable(name, type, nullability);
    }

    private static string AppendNullable(string value, Type type, NullabilityInfo? nullability)
    {
        return !type.IsValueType && nullability?.ReadState == NullabilityState.Nullable
            ? value + "?"
            : value;
    }

    private static string FormatDefault(object? value, Type declaredType)
    {
        if (value is null)
        {
            return declaredType.IsValueType && Nullable.GetUnderlyingType(declaredType) is null
                ? $"default({FormatType(declaredType)})"
                : "null";
        }
        if (value == Missing.Value)
        {
            return "<missing>";
        }
        if (value == DBNull.Value)
        {
            return "<dbnull>";
        }
        if (value is string text)
        {
            return JsonSerializer.Serialize(text);
        }
        if (value is char character)
        {
            return $"U+{(int)character:X4}";
        }
        if (value is bool boolean)
        {
            return boolean ? "true" : "false";
        }
        if (declaredType.IsEnum)
        {
            if (declaredType.IsDefined(typeof(FlagsAttribute), inherit: false)
                && TryFormatFlags(declaredType, value, out var flags))
            {
                return flags;
            }

            var underlying = Enum.GetUnderlyingType(declaredType);
            var numeric = underlying == typeof(ulong)
                ? Convert.ToUInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture)
                : Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
            return $"{FormatType(declaredType)}({numeric})";
        }
        if (value is float single)
        {
            return $"float:0x{BitConverter.SingleToUInt32Bits(single):X8}";
        }
        if (value is double @double)
        {
            return $"double:0x{BitConverter.DoubleToUInt64Bits(@double):X16}";
        }
        if (value is decimal @decimal)
        {
            return @decimal.ToString(CultureInfo.InvariantCulture) + "m";
        }
        return Convert.ToString(value, CultureInfo.InvariantCulture)
            ?? throw new InvalidOperationException($"Cannot format default value {value}.");
    }

    private static bool TryFormatFlags(Type enumType, object value, out string formatted)
    {
        var underlying = Enum.GetUnderlyingType(enumType);
        var unsignedValue = ToUInt64(value, underlying);
        var fields = enumType.GetFields(BindingFlags.Public | BindingFlags.Static)
            .Select(field => (Field: field, Value: ToUInt64(field.GetRawConstantValue()!, underlying)))
            .OrderBy(static item => item.Value)
            .ThenBy(static item => item.Field.Name, StringComparer.Ordinal)
            .ToArray();

        var exact = fields.FirstOrDefault(item => item.Value == unsignedValue);
        if (exact.Field is not null)
        {
            formatted = $"{FormatType(enumType)}.{exact.Field.Name}";
            return true;
        }

        var remaining = unsignedValue;
        var parts = new List<string>();
        foreach (var item in fields.Where(static item => item.Value != 0 && IsPowerOfTwo(item.Value)))
        {
            if ((remaining & item.Value) != item.Value)
            {
                continue;
            }

            parts.Add($"{FormatType(enumType)}.{item.Field.Name}");
            remaining &= ~item.Value;
        }

        if (remaining == 0 && parts.Count > 0)
        {
            formatted = string.Join(" | ", parts);
            return true;
        }

        formatted = string.Empty;
        return false;
    }

    private static ulong ToUInt64(object value, Type underlying)
    {
        return underlying == typeof(sbyte)
            ? unchecked((ulong)Convert.ToSByte(value, CultureInfo.InvariantCulture))
            : underlying == typeof(short)
                ? unchecked((ulong)Convert.ToInt16(value, CultureInfo.InvariantCulture))
                : underlying == typeof(int)
                    ? unchecked((ulong)Convert.ToInt32(value, CultureInfo.InvariantCulture))
                    : underlying == typeof(long)
                        ? unchecked((ulong)Convert.ToInt64(value, CultureInfo.InvariantCulture))
                        : Convert.ToUInt64(value, CultureInfo.InvariantCulture);
    }

    private static bool IsPowerOfTwo(ulong value) => (value & (value - 1)) == 0;

    private static bool IsRequired(this MemberInfo member) =>
        member.IsDefined(typeof(RequiredMemberAttribute), inherit: false);

    private static string FormatSignificantAttributes(MemberInfo member)
    {
        var attributes = new List<(string Name, string Text)>();
        if (member is Type type)
        {
            if (type.IsDefined(typeof(FlagsAttribute), inherit: false))
            {
                attributes.Add((typeof(FlagsAttribute).FullName!, "[System.FlagsAttribute]"));
            }

            var usage = type.GetCustomAttribute<AttributeUsageAttribute>(inherit: false);
            if (usage is not null)
            {
                attributes.Add((
                    typeof(AttributeUsageAttribute).FullName!,
                    string.Concat(
                        "[System.AttributeUsageAttribute(validOn=",
                        FormatDefault(usage.ValidOn, typeof(AttributeTargets)),
                        ", allowMultiple=",
                        FormatDefault(usage.AllowMultiple, typeof(bool)),
                        ", inherited=",
                        FormatDefault(usage.Inherited, typeof(bool)),
                        ")]")));
            }
        }

        var obsolete = member.GetCustomAttribute<ObsoleteAttribute>(inherit: false);
        if (obsolete is not null)
        {
            attributes.Add((
                typeof(ObsoleteAttribute).FullName!,
                string.Concat(
                    "[System.ObsoleteAttribute(message=",
                    FormatDefault(obsolete.Message, typeof(string)),
                    ", error=",
                    FormatDefault(obsolete.IsError, typeof(bool)),
                    ", diagnosticId=",
                    FormatDefault(obsolete.DiagnosticId, typeof(string)),
                    ", urlFormat=",
                    FormatDefault(obsolete.UrlFormat, typeof(string)),
                    ")]")));
        }

        attributes.AddRange(FormatContractAttributes(member.GetCustomAttributesData()));

        return attributes.Count == 0
            ? string.Empty
            : string.Join(' ', attributes.OrderBy(static attribute => attribute.Name, StringComparer.Ordinal)
                .Select(static attribute => attribute.Text)) + " ";
    }

    private static bool HasAttribute(Type parameter, string fullName) =>
        parameter.GetCustomAttributesData().Any(attribute =>
            string.Equals(attribute.AttributeType.FullName, fullName, StringComparison.Ordinal));

    private static byte? GetNullableConstraint(Type parameter)
    {
        var attribute = parameter.GetCustomAttributesData().FirstOrDefault(item =>
            string.Equals(
                item.AttributeType.FullName,
                "System.Runtime.CompilerServices.NullableAttribute",
                StringComparison.Ordinal));
        if (attribute is null || attribute.ConstructorArguments.Count != 1)
        {
            return null;
        }

        var argument = attribute.ConstructorArguments[0];
        if (argument.Value is byte value)
        {
            return value;
        }
        if (argument.Value is IReadOnlyCollection<CustomAttributeTypedArgument> values
            && values.FirstOrDefault().Value is byte first)
        {
            return first;
        }
        return null;
    }

    private static string FormatContractAttributePrefix(IEnumerable<CustomAttributeData> attributes)
    {
        var formatted = FormatContractAttributes(attributes)
            .OrderBy(static attribute => attribute.Name, StringComparer.Ordinal)
            .Select(static attribute => attribute.Text)
            .ToArray();
        return formatted.Length == 0 ? string.Empty : string.Join(' ', formatted) + " ";
    }

    private static IEnumerable<(string Name, string Text)> FormatContractAttributes(
        IEnumerable<CustomAttributeData> attributes)
    {
        foreach (var attribute in attributes)
        {
            var name = attribute.AttributeType.FullName;
            if (name is null || !ContractAttributeNames.Contains(name))
            {
                continue;
            }

            var arguments = attribute.ConstructorArguments
                .Select(FormatAttributeArgument)
                .Concat(attribute.NamedArguments
                    .OrderBy(static argument => argument.MemberName, StringComparer.Ordinal)
                    .Select(argument => argument.MemberName + "=" + FormatAttributeArgument(argument.TypedValue)))
                .ToArray();
            var suffix = arguments.Length == 0 ? string.Empty : "(" + string.Join(",", arguments) + ")";
            yield return (name, "[" + name + suffix + "]");
        }
    }

    private static string FormatAttributeArgument(CustomAttributeTypedArgument argument)
    {
        if (argument.Value is null)
        {
            return "null";
        }
        if (argument.Value is IReadOnlyCollection<CustomAttributeTypedArgument> values)
        {
            return "[" + string.Join(",", values.Select(FormatAttributeArgument)) + "]";
        }
        if (argument.Value is Type type)
        {
            return "typeof(" + FormatType(type) + ")";
        }
        if (argument.Value is string text)
        {
            return JsonSerializer.Serialize(text);
        }
        if (argument.Value is char character)
        {
            return $"U+{(int)character:X4}";
        }
        if (argument.Value is bool boolean)
        {
            return boolean ? "true" : "false";
        }
        if (argument.ArgumentType.IsEnum)
        {
            return FormatDefault(argument.Value, argument.ArgumentType);
        }
        return Convert.ToString(argument.Value, CultureInfo.InvariantCulture)
            ?? throw new InvalidOperationException("Cannot format a contract attribute argument.");
    }

}
