<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Orleans.SearchableStorage.Qualification.SkyPulse.CorpusBuilder</AssemblyName>
    <RootNamespace>Orleans.SearchableStorage.Qualification.SkyPulse.CorpusBuilder</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Orleans.SearchableStorage.Qualification.SkyPulse.Core/Orleans.SearchableStorage.Qualification.SkyPulse.Core.csproj" />
  </ItemGroup>
</Project>
