<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Orleans.SearchableStorage.Qualification.SkyPulse.DurableIngestion/Orleans.SearchableStorage.Qualification.SkyPulse.DurableIngestion.csproj" />
    <ProjectReference Include="../../src/Orleans.SearchableStorage.Qualification.SkyPulse.CorpusAcquisition/Orleans.SearchableStorage.Qualification.SkyPulse.CorpusAcquisition.csproj" />
    <ProjectReference Include="../../src/Orleans.SearchableStorage.Qualification.SkyPulse.CorpusBuilder/Orleans.SearchableStorage.Qualification.SkyPulse.CorpusBuilder.csproj" />
  </ItemGroup>
</Project>
